### PR TITLE
GameOfLife Example

### PR DESCRIPTION
**Pull request by nubtwo**
hope you like it

Greetings from Germany

### CODE REVIEW

**Comment by nubtwo** [comment]
Are further improvements/adjustments needed? Let me know.

**Comment by Gadgetoid** [comment]
Honestly- I haven't had the chance to test/merge it yet. Sorry to leave you hanging.

I don't think `stickler-ci` will report status unless you merge the current `scroll-phat-hd` master into your branch, but I can run those checks when I get around to merging it anyway.

**Comment by nubtwo** [comment]
No problem at all. Just let me know what needs improving - superb learning experience.

**Comment by Gadgetoid** [comment]
Brilliant stuff! Thank you.

I made a quick change to swap `import scrollphathd as phat` with simply `import scrollphathd` since we favour clarity over ease of typing in examples. Also ran flake8 and split a multi-import onto two lines and removed one instance of trailing whitespace- nothing major!

Works great! Danke schon!

**Pull request merged**
