### PR TITLE
Simple Cellular Automata with scrollphatHD

### PR DESCRIPTION
**Pull request by pbpraha**
it's MrGJones' fault... all of it!

simpleCA.py == simple gui
CA.py (requires CA_support.py) == advanced gui

references :
https://en.wikipedia.org/wiki/Rule_30
https://en.wikipedia.org/wiki/Elementary_cellular_automaton

please excuse my python, i'm new here ;)

### CODE REVIEW

**Comment by Gadgetoid** [comment]
This is some incredible stuff, and I heartily recommend you set up your own GitHub repository to include this example and perhaps some documentation since it's quite advanced and could form the basis of something people could adapt to other HATs/pHATs/Displays.

As for submitting here, I'd love to include this but it's a little too complicated to work well as an example for Scroll pHAT HD. I think it could be refined to fit, though, if you;

1. Simplify it down to just display a sequence of different CA rules on Scroll pHAT HD automatically, with no GUI
2. Add command-line options for choosing a particular rule, speed and to randomise the starting point

It's totally up to you should you accept this challenge, but this is cool stuff and I'd love to be able to include it.

Thank you!

**Comment by pbpraha** [comment]
Hello Philip

Thanks for the reply and thanks for a great little gadget, I haven't had so
much fun in years !

I'll refactor the code as you suggest and re-submit a pull.  I'll have to
look into setting up a repository, this Git stuff is all new to me.

Cheers

Paul

**Comment by Gadgetoid** [comment]
New is good. If I someone convince you to pick up a new skill and dive into GitHub, that's great :D

We have a forum-member working on a guide which might help you: https://github.com/Tom-Archer/github-contrib  (related forum thread: http://forums.pimoroni.com/t/github/4643)

**Comment by pbpraha** [comment]
@Gadgetoid 

I've reworked the script into a new file > verySimpleCA.py
This one has no ui, just loops through a bunch of interesting CA as you suggested and has an better explanation of what's going on with the code. CL exercise is left for the reader ;)

**Comment by Gadgetoid** [comment]
Awesome stuff, thank you!

I've cherry-picked `verySimpleCA.py` from this Pull Request, tidied it up a little to better reflect our style guidelines and renamed to `cellular-automata.py`.

Really great work here, I appreciate the exhaustive documentation that seems to put mine to shame ;)

This thing is fascinating to watch, I might leave it running for a while!

**Comment by pbpraha** [comment]
LOL

Glad you like it mate.
I've been fascinated by this stuff since I watched Stephen Wolfram's NKS
lecture, it's worth checking out :)

I now have a new hobby and I don't even have to leave my desk - win!

**Pull request merged**
