### PR TITLE
Attempt to use SMBus2 when SMBus is not available

### PR DESCRIPTION
**Pull request by Bertware**
SMBus2 is pure python and can be installed in environments where SMBus cannot be (easily) installed, such as projects based on buildroot.

https://pypi.org/project/smbus2/

### CODE REVIEW

**Comment by Gadgetoid** [comment]
You know I'm almost tempted just to use `smbus2` across everything. In many cases I prefer it because of the `i2c_rdwr` method and I've not had any reported issues with it to date. It would save needing fallbacks like this, and could just be included as a dependency. What do you think?

**Comment by Bertware** [comment]
That would work just as well for me, assuming performance is the same (I'm not familiar with the exact differences between C python modules and native python modules).

**Comment by Gadgetoid** [comment]
I would guess the performance difference is minimal, it should be really easy to test... maybe I'll give that a shot since it could be interesting information to inform how we approach this.

That said... i2c isn't exactly reknown for throughput and I struggle to think of many scenarios where a loss in performance attributed to using CFFI in lieu of direct C bindings would be an issue. I think libraries like SMBus don't really make much use of C's strengths in this case- IE: they are small, simple functions which do one thing (set up and fire off the ioctl for i2c iirc) and 99% of the cost is in the function call itself. So it boils down to whether setting up and calling directly via CFFI is meaningfully slower than calling a C function.

**Comment by Gadgetoid** [comment]
I guessed correctly. We're talking a penalty of about 40uS (.04ms) for a 32-byte read in `smbus2` vs `smbus`.

Methodology:

```
pi@raspberrypi:~/smbust $ cat smbus-test.py
from smbus import SMBus

ADDR = 0x39

bus = SMBus(1)

for x in range(10000):
    bus.read_i2c_block_data(ADDR, 0x00, 32)

pi@raspberrypi:~/smbust $ perf_4.9 stat -r 10 -B python3 smbus-test.py

 Performance counter stats for 'python3 smbus-test.py' (10 runs):

        546.795314      task-clock:u (msec)       #    0.017 CPUs utilized            ( +-  1.42% )
                 0      context-switches:u        #    0.000 K/sec
                 0      cpu-migrations:u          #    0.000 K/sec
               581      page-faults:u             #    0.001 M/sec                    ( +-  0.08% )
        95,758,446      cycles:u                  #    0.175 GHz                      ( +-  0.22% )
        90,295,277      instructions:u            #    0.94  insn per cycle           ( +-  0.13% )
        20,075,592      branches:u                #   36.715 M/sec                    ( +-  0.11% )
           664,147      branch-misses:u           #    3.31% of all branches          ( +-  1.31% )

      32.753841434 seconds time elapsed                                          ( +-  0.01% )

pi@raspberrypi:~/smbust $ cat smbus2-test.py
from smbus2 import SMBus

ADDR = 0x39

bus = SMBus(1)

for x in range(10000):
    bus.read_i2c_block_data(ADDR, 0x00, 32)

pi@raspberrypi:~/smbust $ perf_4.9 stat -r 10 -B python3 smbus2-test.py

 Performance counter stats for 'python3 smbus2-test.py' (10 runs):

       1005.359403      task-clock:u (msec)       #    0.030 CPUs utilized            ( +-  1.03% )
                 0      context-switches:u        #    0.000 K/sec
                 0      cpu-migrations:u          #    0.000 K/sec
               654      page-faults:u             #    0.651 K/sec                    ( +-  0.05% )
       360,995,939      cycles:u                  #    0.359 GHz                      ( +-  0.44% )
       297,623,614      instructions:u            #    0.82  insn per cycle           ( +-  0.09% )
        67,642,865      branches:u                #   67.282 M/sec                    ( +-  0.15% )
         2,106,389      branch-misses:u           #    3.11% of all branches          ( +-  1.18% )

      33.199629483 seconds time elapsed                                          ( +-  0.02% )
```

Barely worth caring about!

**Comment by Bertware** [comment]
I tested `bus.write_byte_data(0x61, 0x19, 127)` using your test script on a Raspberry Pi 4. These tests completed in 8.82363 for smbus and 8.86510 for smbus2. This means that smbus2 was 4,14us slower per call (0.04147s per 10,000 calls), a relative difference of 0,46%

The same test on a pi zero resulted in 5.776170348 vs  6.015689580 seconds, a difference of 0.2395s, a difference of 4,14%. The difference per call was 23us. A second test resulted in 5.84 vs 6.01s, a difference of 2,91%.

You got the numbers, time to decide!

**Comment by Gadgetoid** [comment]
These numbers definitely don't worry me. Most sensors have an integration time at least an order of magnitude greater than this and if someone *really* *really* needs high throughput they should probably be writing their application in C anyway.

Standardising on smbus2 across the board would seem like the obvious choice!

Most of our `i2c-device` based libraries actually allow an SMBus object to be passed in, replacing the default- see: https://github.com/pimoroni/i2cdevice-python/blob/60bfa6a989b3f135be84091a95e8af949a8f7034/library/i2cdevice/__init__.py#L164-L166

I could switch all of the libraries based on this one to smbus2 in a single stroke and see how much breaks 😆

**Comment by Gadgetoid** [comment]
Fixed by #75 - thank you!

**Pull request closed without merging**
