### PR TITLE
Create hashtagToScrollPhatHD.py

### PR DESCRIPTION
**Pull request by MrGJones**
this is it.. i can finally see the light!

### CODE REVIEW

**Comment by Gadgetoid** [comment]
Woohoo! Nice work.

Mind pruning out any commented-out lines of code so it's nice and tidy?

Thank you!

**Comment by MrGJones** [comment]
ok mate should be all fixed up now. let me know! 👍

**Comment by Gadgetoid** [comment]
Beautiful! Congratulations! Thou hast been merged. Thank you. I'm going to fire it up and rename the Python file ;)

**Comment by MrGJones** [comment]
ok Philip thank you, i hope people/pirates have fun with it!

ill make further adjustments to it soon :)
glenn

**Comment by Gadgetoid** [comment]
I've made a few tweaks to it. Nothing major- mostly moving the config vars to the top of the script and using `queue.get(False)` for a non-blocking (immediately either gets an item or raises an exception if the queue is empty) main loop

**Comment by MrGJones** [comment]
Cheers phil. Got some more error checking routines to add soon!

**Pull request merged**
